### ISSUE TITLE
Integrating deep linking

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/product#13]
## Description

Implement deep linking throughout Open Enterprise.

### Acceptance Criteria

- [x] Deep linking integrated in Projects
- [x] Deep linking integrated in Dot Voting
- [x] Deep linking integrated in Rewards

## Technical specs

Refer to [Otto's tech specs](https://www.notion.so/autark/Deep-Linking-technical-specs-5e4d6d4518e543af898dd3cf1586dba4#df42897bf20d4996bb236b018d5f2500) for details around the Projects implementation

## Product specs

[Designs available on Figma](https://www.figma.com/file/Jadwd36W3sBipDro1IKB9r/Deep-linking?node-id=0%3A1).

**Comment by ottodevs** [comment]
Just my view on this:

I think the current A1 implementation for voting app is just ignoring invalid vote passed in the path, so instead of errors, the general vote list is rendered in that scenario, without any kind of feedback for the user (I would call this gracefully handle)

I am personally not 100% satisfied with this solution, because a user could feel that the app is not behaving correctly for the intent of loading an specific issue, and would not be very intuitive to figure out that what actually happens is that the issue does not exist. So I think better alternatives would be:
- Specific error views for issues not found / work submissions not found / application submission not found / other path not found (like trying to load: /projects/some_random_path)
- Generic 404 error page for every views (that is probably the most extended solution for this problem in the web world)

**Comment by ottodevs** [comment]
This probably might be a recurrent need also for the rest of the apps, so figuring an integral solution will probably be more efficient

**Comment by ottodevs** [comment]
Related PR for the code side: https://github.com/AutarkLabs/open-enterprise/pull/1679
(It is probably far from perfect, but it is a working approach, it will be improved based on review comments/future needs)

**Comment by javieralaves** [comment]
@stellarmagnet I see this went to ready for implementation. Do we need any product specs for this or to address design needs at this stage, or is this not part of the scope for now? (other than what I can read on the issue's description) Should we define acceptance criteria?

**Comment by stellarmagnet** [comment]
@javieralaves I just updated it to have the acceptance criteria. I was trying to advance stuff up the pipeline so it doesn't seem like product is holding back a particular epic.

No technical review was required because nothing has really changed as far as what was previously described in the children tickets.

**Comment by javieralaves** [comment]
@stellarmagnet @ottodevs If the link can be associated to an app but not to an object within that app (i.e. an issue in Projects or a dot vote in Dot Voting), we can either...

1 - [Display a universal 'Not found'](https://www.figma.com/file/Jadwd36W3sBipDro1IKB9r/Deep-linking?node-id=1%3A70) that sits "outside of the organization" visually speaking, which as a design direction is more similar to the global error designs I've seen from Aragon One (note: these global error designs have not been updated to accommodate for deep linking errors, as Otto pointed out)

2 - [Display an in-app 'Not found' view](https://www.figma.com/file/Jadwd36W3sBipDro1IKB9r/Deep-linking?node-id=1%3A369) that still lives within the app, since the link is able to still recognize the app in which the object was theoretically supposed to be in.

I'd personally prefer the latter. What do you think?

By the way, are we also deep linking bounty-related applications and work submissions? I assume that if we are, we probably need some design input for that too.

**Comment by ottodevs** [comment]
> @stellarmagnet @ottodevs If the link can be associated to an app but not to an object within that app (i.e. an issue in Projects or a dot vote in Dot Voting), we can either...
> 
> 1 - [Display a universal 'Not found'](https://www.figma.com/file/Jadwd36W3sBipDro1IKB9r/Deep-linking?node-id=1%3A70) that sits "outside of the organization" visually speaking, which as a design direction is more similar to the global error designs I've seen from Aragon One (note: these global error designs have not been updated to accommodate for deep linking errors, as Otto pointed out)
> 
> 2 - [Display an in-app 'Not found' view](https://www.figma.com/file/Jadwd36W3sBipDro1IKB9r/Deep-linking?node-id=1%3A369) that still lives within the app, since the link is able to still recognize the app in which the object was theoretically supposed to be in.
> 
> I'd personally prefer the latter. What do you think?
> 
> By the way, are we also deep linking bounty-related applications and work submissions? I assume that if we are, we probably need some design input for that too.

From my perspective I see that is technically more feasible to also take the path for option 2, because if I understand it correctly, option 1 would involve modifications into A1 core repos (like aragon client), and would require generalizing a lot of the logic, thus making the error designs more ambiguous.

Apart from that, it is needed to note that most links pointing to specific content are already associated to an app, in the way a "canonical" aragon link contains:
```
https://rinkeby.aragon.org/#/neudune/0xc5e05c810166af221c2fc79cee2d0a7f288d6a42/
|-------------------------|---------|------------------------------------------|
|  aragon client main url | DAOaddr |                App Address               |
```
Then the rest of the trailing url from that would be the deep link we are managing within the app like for example:
`/issues/<issueId>/work/<workSubmissionId>`

So the client should only manage the errors for the first "canonical section" of the url, and we should manage the "variable section" or in other words, the deep link part of the url.

That is my understanding of how this should be managed, and I think it is aligned what your preference, the second option you propose.

> By the way, are we also deep linking bounty-related applications and work submissions? I assume that if we are, we probably need some design input for that too.

I think yes, this is part of the current spec, we are handling deep-links pointing to specific work submissions and application submissions.

As a final note after reviewing the Figma designs, I think it would be more appropriate to use the "object" terminology or even "content" terminology instead of specific "issue" terminology, because in fact, it can be multiple types of content that can be not found, for example for projects we can have:
- Tab not found
- Issue not found
- Application submission not found
- Work submission not found
- Filter set not found
(that is just for projects)

So yes, I think "content not found would cover all these case so we can keep reusing that screen for each of the possible options, and even for the rest of apps.

**Comment by javieralaves** [comment]
@ottodevs Fantastic suggestion; let's go with the 'content' term then instead of specific terms for now.

**Comment by javieralaves** [comment]
All acceptance criteria has been met for this epic.
