### ISSUE TITLE
Improved cross-application experience with radspec

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#15]
# Description
We need to make enhancements to aragonSDK to improve the cross app UX. This is important so we can display the most relevant information for forwarded actions.

## Acceptance criteria
- [x] Develop a radspec helper so we can display estimated dates for future block numbers or block mining dates for block numbers which exist in the past. (Note: such a helper would be useful outside of radspec, as well, such as the New Reward panel preview or Rewards landing page. I assume that needs slightly different code? @topocount)
- [x] Update the forwarder API POC so it has the latest code from aragon.js
- [ ] Perform research and document the technical spec & implementation plan to improve the radspec for standard bounties
- [ ] Document the technical spec & implementation plan so the radspec for the Projects app provides DAO members with actionable context in the voting app
- [ ] Develop a radspec helper so we can display data associated to a JSON file that is hosted on IPFS in the radspec
