### ISSUE TITLE
Enhanced developer experience for token dropdowns

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#16]
## Description
Implement a token API and token dropdown to make our software development more DRY and also contribute this to the aragonSDK so developers don't have to reinvent the wheel when requiring an amount-based input from users.

### Acceptance criteria
- [x] Write the high-level specifications for the token API
- [ ] Get approval on the architecture from A1
- [ ] Develop the aragonSDK solution based on the approved architecture
- [ ] Submit the PR(s) into the relevant aragon repos
- [ ] Get the PRs merged and reviewed
- [ ] Identify which aspects of our apps need changes (beyond the ones below?)
- [ ] Update our OE apps to utilize the new component & API
  - [ ] Rewards - New Reward
  - [ ] Projects - Settings (Base Rate) 
  - [ ] Projects - Fund issues panel (When fixed funding)
  - [ ] Allocations - New budget
  - [ ] Dot Voting - rendering amounts for allocation dot votes

### Specification
[Google Drive Spec](https://docs.google.com/document/d/1a6Qb9piOJwhGgrNcV2yWrt5vKfXySqhIy7GxQa2ATSc/edit)

**Comment by Quazia** [comment]
This will be reviewed by @topocount

**Comment by javieralaves** [comment]
As pointed out by @stellarmagnet, there's no indication that this will be reviewed or merged into the aragonSDK any time soon. Moving into B3, we have to re-write the the acceptance criteria to accommodate simply for a deliverable composed of a forum thread with a spec and a proof of concept. This will allow us to obtain feedback from the community and make considerations for the future.

**Comment by javieralaves** [comment]
[Awesome stuff](https://forum.aragon.org/t/token-api-specification/1578) @PeterMPhillips. Do we still need an epic for B3, or are we pausing the work on TokenAPI here? @stellarmagnet

**Comment by javieralaves** [comment]
I presume we can close this for now unless we want to continue the work into B3. No signals received from the forum thread as of right now.
