### ISSUE TITLE
Deploying the Token Manager

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/product#20]
## Description
Deploy the Token Manager to Rinkeby and Mainnet.

### Acceptance criteria 
- [ ] Pull the latest code for the token manager in aragon/aragon-apps
 - [ ] Deploy the token manager to Rinkeby and follow our processes for documenting deploys
 - [ ] Test it: Create a new organization with our internal dev Rinkeby key, install the Projects app, Vault, finance, etc.. Whitelist the Vault, the Projects app, and StandardBounties contracts (do we need to whitelist all of them?). Win a bounty. Test that after you receive the token, you can't transfer it.
 - [ ] Document a usage guide for how to add or remove address from the white list.
- [ ] Publish and deploy to Mainnet, and repeat other steps above
