### ISSUE TITLE
Enhanced bounty experience

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#4]
## Description
* The display of bounty-related information should be enhanced to be more intuitive and contextual to the user
* Allow open submission bounties to be created and completed

### Acceptance criteria
This epic will be completed once:
- [x] Issues can be funded and completed without requiring an application
- [x] The 'Status' widget has been replaced with the enhanced 'Bounty' widget
- [x] Bounty related information no longer appears on top of the issue's description in the detail view
- [x] The Activity panel displays the right information in the new format
- [x] Context menus and budget widget are implemented according to the specifications and designs, across the entire bounty experience
- [x] The Issues tab has a new design which includes new icons, and properly handles open submission vs. application require bounties

What's not part of this epic, but in the designs:
* 'Bounties' widget supporting multi-bounty logic
* Additional input per issue related to # of bounties
* Additional filter in the 'View application' and 'View work' panels

These will be covered in other epics.

## Product specs

Available [on Google Drive](https://docs.google.com/document/d/1bCVzG1te86It0cAT110w7MKVi5_1Df0M-eX5ado1yyY/edit?usp=sharing).

**Comment by javieralaves** [comment]
@chadoh I'd like to get your thoughts on this as well especially on how this affects the Issues tab view across screen sizes. Updates are available on the [exploration branch](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=330%3A0) for as long as the product specs are being reviewed by Yalda; either way there'll be changes in how the Issues tab looks as far as the information displayed per issue. On this view, what I've done is mainly:
* Sync texts and icons between this view and the new bounty views
* Update the way we handle this information on mobile, adjusting paddings and making it more cohesive with what's displayed on desktop. As I've commented, you'll notice that the issues start to get pretty large on the y-axis when all the info is displayed. My proposal for an upcoming release would be to either hide some of the info or display it in some sort of expanded row. Would appreciate your thoughts on this particular topic too before we go deeper into it

**Comment by stellarmagnet** [comment]
@jayalaves great work! I provided comments in the Figma, but am still mid-review. I know you have a lot of designs for the various use cases of how the Bounty widget should look, but having written specifications is also important.

Some use cases to consider:
* Deadline is in the past and nobody fulfilled the bounty
* Deadline is in the past and somebody fulfilled the bounty (e.g. it says something like `Completed 6 days ago` ?)
* What does the deadline look like when in the past and multiple people completed it?
* Multiple people being assigned the bounty
* Multiple people completing the bounty
* People being assigned the bounty, yet deadline in the past
* Closed Github tickets (with active or inactive bounties)

**Comment by javieralaves** [comment]
@stellarmagnet Thank you for all the comments and feedback! I've taken all the specs into Google Drive and updated the issue here with a task list of the pending changes I have to make on Figma before I can give the product specs another round. 

As far as having logic around more than one contributor to a bounty – I thought about setting that up over a different epic because otherwise I think this will become a very heavy spec to navigate. So I'd focus on everything related to multi-contributor logic on a separate topic.

**Comment by javieralaves** [comment]
@stellarmagnet Just wrapped up the following:
* Added 'Acceptance criteria' section on the issue, is this in line with what you were suggesting?
* Updated specs to be specifically about component changes & linked to new section on Figma
* Several updates made on the design's exploration branch
* Previous specs are in the same Drive folder to go over a later iteration once I advance with the rest of the backlog

**Comment by stellarmagnet** [comment]
@javieralaves thank you for the updates! 

I added a few comments to the Figma and to the specs! I feel like I'm just getting into the weeds & edge cases, and we can hash out a lot of this in a quick meeting. Ping on keybase for the earliest you are free to go over some of this? Maybe monday morning at 10am?

The acceptance criteria looks good, I made a couple tweaks. I was confused by what this means though:
> * Information layout for the main column fits the design

**Comment by javieralaves** [comment]
@stellarmagnet thank you for your review!

I've made a few changes here and there, accepted your suggestions, and updated this ticket to mention what needs to be further discussed over a call and pending design changes on Figma that I'll go over tomorrow. We can discuss further during our call at 14:30, otherwise I'm also free on 10:00 as you've asked. I'll send you a cal invite!
