### ISSUE TITLE
Bounties tab

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#44]
## Description

Enable a 'Bounties' tab where users have a view-only Kanban board displaying four pipelines related to bounty management across all issues.

### Acceptance criteria

- [ ] The 'Bounties' tab is available from within the general tab bar area
- [ ] Three pipelines available: 'Accepting applications', 'Accepting work submissions' and 'Review'
- [ ] Issues are sorted automatically by creation date ascending (newest first) across pipelines
- [ ] Issues can be clicked on to navigate directly to the issue detail view
- [ ] Pipeline navigation on mobile is intuitive, either with horizontal swiping, or an mobile dropdown for pipelines

### Product specs

[Available on Google Drive.](https://docs.google.com/document/d/1GuxCa5dIFrV3ZTLvOOYVgvhdS6uDH9VtN7J2E8WkpDI/edit?usp=sharing)

**Comment by javieralaves** [comment]
@stellarmagnet @Quazia I've [started designing some views](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1246%3A22713) for the upcoming specs for this epic. I've illustrated a concept for the 'project detail view' with a single filter and a search component on the tab bar. We could have more filters here depending on whether we've been able to resolve the issues with filtering. I've also done some MVP illustrations for the 'Bounties' tab, which is a view-only tab with four pipelines. Ideally, users can click on issues taking them to the issue detail view, or to a nested kanban view with pipelines for application management.

I'm not too happy with how pipelines look having tried to mold them into aragonUI styles, but I guess it works well as MVP and we can consider visual enhancements later on.

**Comment by javieralaves** [comment]
@stellarmagnet Epic specifications are ready for your product review.

**Comment by stellarmagnet** [comment]
@javieralaves I added a few comments to the design and spec! Back at you for review.

**Comment by javieralaves** [comment]
@stellarmagnet Did you have a chance to review [the latest design](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1713%3A24714)? I think that you may have reviewed the wrong frame because I kept the legacy designs there for reference :)

![Bounties tab concept design.png](https://images.zenhubusercontent.com/5cf4fe30c7859b3c51c81634/dcdd56ee-9a1f-4629-8587-2bd798a99791)

**Comment by stellarmagnet** [comment]
@javieralaves ahh, I missed that, thank you!

**Comment by stellarmagnet** [comment]
@javieralaves I added a few more comments! Let's move this to technical review so the dev team can start reviewing it. The remaining comments seem like they can be addressed in parallel or they require input from devs.

**Comment by javieralaves** [comment]
Some components still undergoing some minor design reviews:

- Pipeline column design
- Information displayed in the pipeline issue card

**Comment by javieralaves** [comment]
Note: Edited column structure to be three instead of four columns, removing the 'Not funded' pipeline.

**Comment by javieralaves** [comment]
All issues have been reviewed and closed. Awesome work @PeterMPhillips and anyone else involved!
