### ISSUE TITLE
Add multiple bounties per funded issue

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#46]
## Description

Allow a funded issue to have more than one bounty associated to it.

### Acceptance criteria

- [ ] Issues in the 'Fund issues' panel have an additional input to specify number of bounties
  - [ ] 'Number of bounties' is a mandatory input that is required to proceed. It will be populated with the value of 1 by default.
  - [ ] Only positive integers are allowed as input, no other input can be inserted
  - [ ] 'Number of bounties' acts as a multiplier on the total amount of funding for an issue
  - [ ] 'Number of bounties' includes a help component that explains how multiple bounties work
- [ ] New icon+text in the Issues tab per issue for number of bounties
- [ ] New rendering of the bounty amount in the issues in the Issues tab, displaying the currency + the amount
- [ ] 'Bounty' widget evolves into 'Bounties' widget when there is more than one bounty
  - [ ] The applications/work submissions section is now an expandable row with addresses as items
  - [ ] Applications can be submitted for as long as there are bounties that haven't been disbursed
- [ ] Available options to engage with the bounty either through the bounty widget or through the context menu are presented conditional to who the viewer is and its activity history with the bounty

### Product specs

[Available on Google Drive.](https://docs.google.com/document/d/1t8DN885S8_ZMQ1Z_efjZlJZwhM3n24OZc5xBIcpbWE4/edit?usp=sharing)

**Comment by javieralaves** [comment]
@stellarmagnet This is ready for your review. I've written the acceptance criteria, [made changes on Figma](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1364%3A90), and edited the specifications on Google Drive. While there are a few additional design tweaks that can be included (i.e. the new filter dropdown in the 'View applications' panel) I decided not to include all of it into the specs nor the acceptance criteria to have this focus entirely on enabling multiple bounties, and will create separate tickets in the near future once I get into testing mode with the deployments for this week.

**Comment by stellarmagnet** [comment]
@javieralaves I finished my review and clarified some of the specs. Just a couple minor details remaining!

**Comment by javieralaves** [comment]
@stellarmagnet Made changes to the specs and to the Figma designs in the spec branch. I've followed your previous feedback, and think this version should be safe enough to try!

**Comment by javieralaves** [comment]
@stellarmagnet I reviewed the latest changes with @rkzel this morning. He mentioned some further research was needed today in order to determine whether there are any difficulties with the contract. Radek, please give us an update here when you have a chance. Also, we discussed shaping this epic down a little in order to meet the deadline for this sprint and ship something by the end of the year perhaps. Maybe not having the expanded row in the bounty widget, as it's not entirely necessary for the functional UX.
