### ISSUE TITLE
Informative dot votes

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#48]
## Description

Enable the user to create a 'New dot vote' from the Dot Voting app to poll the organization's users on informational topics. These votes will not distribute any capital.

### Acceptance criteria

- [x] The empty card should say 'No dot votes here' and include a 'New dot vote' button
- [x] After there is at least one Dot Vote, a 'New dot vote' button is available in the header, and once clicked it opens the 'New dot vote' panel
- [x] The 'New dot vote' panel includes a Description, and Options, both mandatory to submit a vote. The options are just regular text, not Ethereum addresses.
  - [x] The same text cannot be inserted twice as an option on the same dot vote
- [x] Filtering for dot votes includes the Dot Voting app
- [x] Once a dot vote that was created from either the Dot Voting app or Projects app is closed, don't display an 'Execute vote' button and don't display "Pending" in the status. The dot vote detail view will look the same as a Projects issue curation vote.

### Product specs

[Designs available on Figma](https://www.figma.com/file/NZQk49jsqKMHdWxsEwSxJs5n/Dot-Voting?node-id=923%3A6413) on the _Experimental_ branch.

#### Dot vote options

- It should not be permitted to insert the same text twice on the same dot vote. If the user tries to insert the same text twice, show a standard error message with the text "The same option cannot be specified twice."

**Comment by javieralaves** [comment]
@stellarmagnet This is ready for review. I didn't write any particular specifications for this epic other than two simple views on Figma to show the additional button and the 'New dot vote' panel configuration.

**Comment by stellarmagnet** [comment]
@javieralaves looks good! I made one comment in the Figma on whether we should limit the character count for the options (and perhaps description? actually not sure we do it for description anywhere). Additionally, I updated the acceptance criteria to clarify a few points.

**Comment by javieralaves** [comment]
Awesome, thanks @stellarmagnet! I've added also a tiny detail to the acceptance criteria to make sure that the same text cannot be added twice as an option on the same dot vote.

**Comment by javieralaves** [comment]
All issues have been closed after testing.
