### ISSUE TITLE
Decentralized Projects app features

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#54]
## Description

Decoupling Projects minimum viable product from the need to connect to GitHub.

### Acceptance criteria

- [x] New placeholder view, which allows users to use the Projects app without GitHub
- [ ] 'New project' panel allows users to switch between decentralized projects and GitHub
  - [ ] If user is not connected to GitHub, request to connect will appear as designed
- [ ] Project card displays bounties instead of commits
- [ ] Project card displays GitHub identifier for GitHub projects
- [ ] Detail view filter bar displays Labels and Milestones filters conditionally depending on project source
- [ ] Breadcrumb filters appear below the filter bar instead of within it, styled as designed
- [ ] New issues for decentralized projects can be added, edited and removed
- [ ] Issues with bounties in progress cannot be edited or removed
- [ ] The 'GitHub' widget in the Settings tab is updated to match the new design, including a disconnected state
- [ ] For decentralized projects: whenever a username is displayed, such as in the Activity widget and application/work submission panels, IdentityBadges/custom labels will be displayed in place of GitHub profiles

### Specifications

[Available on Google Drive.](https://docs.google.com/document/d/1r1iwltKioiQRsG3k-AK3wNWetUZ9Mc4fCJTvcz_fEoc/edit?usp=sharing)

**Comment by javieralaves** [comment]
@stellarmagnet Epic specifications are ready for your product review.

**Comment by stellarmagnet** [comment]
@javieralaves really nice work! I added some comments to the Gdoc and Figma. I pasted the acceptance criteria into the Gdoc so you can see some of my feedback on those, as well.

**Comment by javieralaves** [comment]
@stellarmagnet Thanks for all of your feedback! I've addressed all of your comments and made all the necessary updates on Figma. It would be great if you could provide additional thoughts on remaining unknowns in the specs. Left a few questions there.

**Comment by stellarmagnet** [comment]
@javieralaves I added a few comments that can be refined in parallel to technical review, as they are just minor clarifications and some of them require dev input regardless. So let's move it forward in the pipelines :)

**Comment by javieralaves** [comment]
@stellarmagnet Perfect, I updated the acceptance criteria to match the latest from the specs, and moving this to technical review. Assigning @Quazia to revise.

**Comment by javieralaves** [comment]
Some components still undergoing some minor design reviews:

- Activity panel integration with `IdentityBadge`
- 'New project' panel, deciding on the design approach to placing GitHub option

cc @chadoh

**Comment by javieralaves** [comment]
@stellarmagnet Based on Chad's evaluation and feedback of the designs I'm processing a minor tweak to the 'New project' panel design that makes the whole dynamic more intuitive, which you [can see here](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1866%3A24893).

**Comment by javieralaves** [comment]
@Quazia Not sure whether the entire acceptance criteria is covered by the existing issues, but certainly it's all the must haves. We can cover the rest if enough time.
