### ISSUE TITLE
Update our documentation

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#56]
## Description

Update our documentation on GitBook and GitHub to match the latest features and updates.

### Acceptance criteria

- [ ] Cover essential information on how to use the apps
- [ ] How to install our apps on existing DAOs, including setup recommendations
- [ ] Permissions glossary for all app permissions with definitions
- [ ] Additional information section per app with warnings and limitations
