### ISSUE TITLE
Improved Allocations interface

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#6]
## Description

Improving the Allocations interface with several enhancements and new information displays, including accounting period metrics, a filters bar, new buttons, and a new budget card design.

### Acceptance criteria
- [x] Added "Deactivate/Activate budget" functionality
- [x] Added the Budget detail view, which should be a deep link, and which should have a different layout for deactivated budgets
- [x] Integrated filters bar with a 'Status' filter
  - [x] Adopted new pattern for 'New allocation' and 'New budget' buttons 
  - [x] Fixed issue of blank screen when trying to create a 'New allocation'
- [x] Updated the budget card design, with alternate design & context menu for deactivated, and improved margins on tablet-and-smaller-sized screens
- [x] New allocation panel: update how we articulate on 'Available Funds' instead of current two-liner
- [x] Numbers and dates are rendered in a consistent format as specified
- [x] Added info box and "every 30 days" to New Budget panel

### Descoped for future epic

* [Display hours as metric when less than a day remaining](https://github.com/AutarkLabs/open-enterprise/issues/1725)
* ['Period info' displayed in main view](https://github.com/AutarkLabs/open-enterprise/issues/1726)
* [Sorting component for budget cards](https://github.com/AutarkLabs/open-enterprise/issues/1727)
* ['Spending since creation' (requires contract-level change)](https://github.com/AutarkLabs/open-enterprise/issues/1728)

## Product specs

[Available on Google Drive](https://docs.google.com/document/d/1tSKskxkaJQZZAhilC8xh2jjYxLJxkUqOhCn071pHAN0/edit?usp=sharing).

**Comment by stellarmagnet** [comment]
Hey @jayalaves. I added some comments to the Figma, just some minor polishing! Some of it also relates to ensuring the specs have enough details for development. I’m reiterating some of the spec-related comments below.

### Accounting period metrics
**Budgeted**: We need clearer specs with the logic behind the currency that is displayed and what we do when an exchange rate doesn’t exist. Since Finance lists in USD as default, I think we should do that.

**Duration**: We need clearer specs on when this says “days” or “weeks”, etc. I think if we just go with days all around, it will be easier to implement for now.

### Filters bar
I'm kind of leaning toward `Active` being default selected... hmm. Anyone else have thoughts? @chadoh @e18r @PeterMPhillips

**Comment by javieralaves** [comment]
@stellarmagnet I've just refined the design and updated the specs for this. Ready for your review! I agree, let's reflect duration in days and set the filter to Active by default. Check out the Experimental branch, I've started some work around how to display information related to organization tokens in the Accounting period metrics section for now.

**Comment by stellarmagnet** [comment]
@javieralaves, great advancements here. I fleshed out some of the specs, and have a few questions as well. I also added a few more comments on the designs... almost there :)

**Comment by javieralaves** [comment]
@stellarmagnet Thank you for your feedback and additional details to the specs! Just a few minor edits left on Figma and this should be ready to go!

**Comment by chadoh** [comment]
>  `Active` being default selected

Makes sense to me.

I added some comments to the Figma and the Google Doc. Much of it is probably stuff to think about and act on later. I think the design and spec seem pretty well-defined right now, and we can work on them mostly as-is, with some of my more minor questions answered.

**Comment by javieralaves** [comment]
@chadoh Addressed most of your comments and suggestions. Thank you, they were very thoughtful and helpful! Let me know if you still need any clarifications.

**Comment by chadoh** [comment]
@javieralaves @stellarmagnet 

> Descoped: 'Period info' displayed in main view

What does this mean? Is this different from the 'Accounting period metrics' section?

**Comment by stellarmagnet** [comment]
@chadoh I can see how you are confused, as I believe there is nothing in the spec or design about that feature exactly. It has to do with showing the exact start date / end date / blocks on the landing page vs. the budget detail page (since it is the same for all budgets). @javieralaves maybe there is a better way to track descoped features?

**Comment by javieralaves** [comment]
I'll get into the practice of proactively creating tickets for descoped material, hyperlinking those tickets here for reference, and including a description there for more specific details on what exactly is being descoped. Have a look at the section now and let me know if that helps :)

**Comment by javieralaves** [comment]
@chadoh What's your estimation for completed acceptance criteria by EOD Dec 12th?

**Comment by javieralaves** [comment]
Updated the acceptance criteria to reflect a slippage on #1576 and #1763. The latter wasn't in the original scope of the epic.

**Comment by javieralaves** [comment]
Having reviewed all issues associated to this epic and cross-verifying with the acceptance criteria, I can confirm that all conditions have been met and we can now close this epic! Thank you for coordinating this @chadoh!
