### ISSUE TITLE
Experimental Open Enterprise

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#7]
## Description

Releasing a version of Open Enterprise with an experimental features template to display work that didn't get merged into the main client yet.

### Acceptance criteria

- [ ] Address Book is integrated as the identity provider
  - [ ] Address Book entities across other apps display the Address Book name instead of the address
  - [ ] Address Book entities are identified upon typing in the 'New allocation' panel
- [ ] 3Box is integrated as a user profile
  - [ ] The user profile can be accessed by hovering over the user address on the client header
  - [ ] The AddressBadge for 3Box-enabled profiles renders the 3Box profile picture and a 3Box label
  - [ ] The user profile works well across desktop, tablet and mobile views
- [ ] Discussions are embedded into dot votes
  - [ ] Users are able to post, edit and remove comments on dot votes
  - [ ] A count of the total number of comments is displayed on dot vote cards and in the detail view
- [ ] The Organization app is replaced with our new version
  - [ ] The home page of the organization can be changed to any other app
  - [ ] Basic information about the organization can be saved, including a name, website and description
    - [ ] The website field only always valid URLs, otherwise changes cannot be saved
  - [ ] The organization's brand can be updated, including being able to upload a custom logo and an accent color
    - [ ] The accent color can either be a solid or gradient style
    - [ ] The accent color can be previewed before it's saved
  - [ ] The Organization app works well across desktop, tablet and mobile views

## Product specs

[Available on Google Drive.](https://docs.google.com/document/d/1bS4tfPwxIBSW-DLsJZxDUwI5sAeP4bPi37NU_r4kMMI/edit?usp=sharing)

**Comment by javieralaves** [comment]
@stellarmagnet This is ready for review. I've essentially worked on defining some specs for the Organization app given the latest design changes based on Paty's feedback.

**Comment by stellarmagnet** [comment]
@javieralaves  thank you for putting this together, things are coming together nicely. 

I added some feedback to the Figma and spec - no major design changes needed, but there are a few things that need to be clarified.

Some additional comments:
* The acceptance criteria in this epic is really broad, I think each feature may require more detailed criteria (for example, `Organization app should be compatible with desktop, tablet, and mobile resolutions`, or `The correct defaults are populated for the Organization app`). I suggest re-evaluating what you have and determining if there is enough information to go off of for the final check-list.

**Comment by javieralaves** [comment]
@stellarmagnet Thanks for all of your feedback, I've modified the acceptance criteria, made changes on Figma for Organization app and Discussions, and updated the specs. It's all ready for product review.

**Comment by javieralaves** [comment]
Moving this to 'In Progress' as I'm presuming no immediate need for additional designs is needed.
