### ISSUE TITLE
Improved onboarding experience

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/product#9]
## Description

Improving the onboarding process by providing better information around configuring gas prices and better animated visual feedback around the signature process.

### Acceptance criteria

- [x] Loader indicators display animated circular progress bar to reflect estimated progress
- [x] 'Waiting for signature' and 'Transaction in progress' are bundled in a single step, rendering the text conditionally
- [x] 'Transaction in progress' includes an estimated time for completion
- [x] The info component in the left menu has been modified to reflect the updated description and style

## Product specs

[Available on Google Drive](https://docs.google.com/document/d/1LOE-gC8OqX1MmJF0Wty5vmevoidxW3PV8VzRbUi_res/edit?usp=sharing).

**Comment by javieralaves** [comment]
@stellarmagnet Ready for product review!

**Comment by stellarmagnet** [comment]
@javieralaves done with the product review! Just a couple tweaks left, but this is ready for tech review.

**Comment by javieralaves** [comment]
@stellarmagnet Comments addressed, we're good to go.

**Comment by stellarmagnet** [comment]
Thanks @javieralaves! Just a few more minor tweaks I noticed in the design - commented.

**Comment by javieralaves** [comment]
@stellarmagnet Got it! By the way, the latest comments are unrelated to this epic, so we probably shouldn't cover them here.

**Comment by javieralaves** [comment]
@e18r Please inform when updates have been merged to dev so we can do acceptance testing.

**Comment by javieralaves** [comment]
Pulling this back to 'In progress' until we address changes related to aragon#32.
